server:
  port: 8080
  servlet:
    context-path: /travel
logging:
  level:
    liquibase: OFF
spring:
  application:
    name: klm-order-case
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:travel-api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  liquibase:
    enabled: true
    user: sa
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: metrics
  endpoint:
    metrics:
      enabled: true
